"""Generate tailored resume as DOCX and PDF."""
import io
from datetime import datetime

def build_docx(tailored: dict, candidate_name: str = "Candidate") -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    for section in doc.sections:
        section.top_margin    = Inches(0.7)
        section.bottom_margin = Inches(0.7)
        section.left_margin   = Inches(0.8)
        section.right_margin  = Inches(0.8)

    def heading(text, size=13, color=RGBColor(0x1d, 0x4e, 0xd8)):
        p   = doc.add_paragraph()
        run = p.add_run(text)
        run.bold           = True
        run.font.size      = Pt(size)
        run.font.color.rgb = color
        p.paragraph_format.space_before = Pt(10)
        p.paragraph_format.space_after  = Pt(2)
        return p

    def divider():
        p   = doc.add_paragraph()
        run = p.add_run('─' * 90)
        run.font.size      = Pt(7)
        run.font.color.rgb = RGBColor(0xcc, 0xcc, 0xcc)
        p.paragraph_format.space_before = Pt(0)
        p.paragraph_format.space_after  = Pt(4)

    def body(text, size=10):
        p   = doc.add_paragraph()
        run = p.add_run(text)
        run.font.size = Pt(size)
        p.paragraph_format.space_before = Pt(2)
        p.paragraph_format.space_after  = Pt(2)
        return p

    # Name
    name_p = doc.add_paragraph()
    name_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    nr = name_p.add_run(candidate_name)
    nr.bold      = True
    nr.font.size = Pt(20)
    nr.font.color.rgb = RGBColor(0x1e, 0x29, 0x3b)

    # Summary
    if tailored.get('summary'):
        heading("PROFESSIONAL SUMMARY")
        divider()
        body(tailored['summary'])

    # Skills
    skills = tailored.get('skills', [])
    if skills:
        heading("SKILLS")
        divider()
        chunks = [skills[i:i+4] for i in range(0, len(skills), 4)]
        for chunk in chunks:
            body("  •  ".join(chunk))

    # Experience
    experience = tailored.get('experience', [])
    if experience:
        heading("EXPERIENCE")
        divider()
        for exp in experience:
            p   = doc.add_paragraph()
            r1  = p.add_run(f"{exp.get('title','')}  ")
            r1.bold = True; r1.font.size = Pt(11)
            r2  = p.add_run(f"@ {exp.get('company','')}")
            r2.font.size = Pt(11)
            r2.font.color.rgb = RGBColor(0x37, 0x8a, 0xdd)
            dp  = doc.add_paragraph(exp.get('duration',''))
            dp.paragraph_format.space_before = Pt(0)
            dp.paragraph_format.space_after  = Pt(2)
            dp.runs[0].font.size = Pt(9)
            dp.runs[0].font.color.rgb = RGBColor(0x88, 0x87, 0x80)
            for bullet in exp.get('bullets', []):
                bp  = doc.add_paragraph(style='List Bullet')
                brun = bp.add_run(bullet)
                brun.font.size = Pt(10)
                bp.paragraph_format.space_before = Pt(1)
                bp.paragraph_format.space_after  = Pt(1)

    # Education
    education = tailored.get('education', [])
    if education:
        heading("EDUCATION")
        divider()
        for edu in education:
            p  = doc.add_paragraph()
            r1 = p.add_run(f"{edu.get('degree','')}  ")
            r1.bold = True; r1.font.size = Pt(11)
            r2 = p.add_run(f"— {edu.get('institution','')}  {edu.get('year','')}")
            r2.font.size = Pt(10)
            r2.font.color.rgb = RGBColor(0x88, 0x87, 0x80)

    # Footer
    fp  = doc.add_paragraph()
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fp.paragraph_format.space_before = Pt(20)
    fr  = fp.add_run(f"Generated by JobScraper Pro · {datetime.now().strftime('%d %b %Y')}")
    fr.font.size = Pt(8)
    fr.font.color.rgb = RGBColor(0xbb, 0xb9, 0xaf)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def build_pdf(tailored: dict, candidate_name: str = "Candidate") -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 not installed. Run: pip install fpdf2")

    class PDF(FPDF):
        def header(self):
            pass
        def footer(self):
            self.set_y(-12)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, f'Generated by JobScraper Pro  |  {datetime.now().strftime("%d %b %Y")}  |  Page {self.page_no()}', align='C')

    pdf = PDF()
    pdf.add_page()
    pdf.set_margins(18, 18, 18)
    pdf.set_auto_page_break(auto=True, margin=18)

    # ── Name ──────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 12, candidate_name, align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    def section_title(title):
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(29, 78, 216)
        pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(200, 200, 200)
        pdf.line(18, pdf.get_y(), pdf.w - 18, pdf.get_y())
        pdf.ln(3)
        pdf.set_text_color(30, 41, 59)

    def body_text(text, size=10):
        pdf.set_font("Helvetica", "", size)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(0, 5, text)
        pdf.ln(1)

    # ── Summary ───────────────────────────────────────────────────────────
    if tailored.get('summary'):
        section_title("PROFESSIONAL SUMMARY")
        body_text(tailored['summary'])

    # ── Skills ────────────────────────────────────────────────────────────
    skills = tailored.get('skills', [])
    if skills:
        section_title("SKILLS")
        chunks = [skills[i:i+5] for i in range(0, len(skills), 5)]
        for chunk in chunks:
            body_text("  •  ".join(chunk))

    # ── Experience ────────────────────────────────────────────────────────
    experience = tailored.get('experience', [])
    if experience:
        section_title("EXPERIENCE")
        for exp in experience:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(30, 41, 59)
            pdf.cell(0, 6, f"{exp.get('title','')} @ {exp.get('company','')}", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(136, 135, 128)
            pdf.cell(0, 5, exp.get('duration',''), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(30, 41, 59)
            pdf.set_font("Helvetica", "", 10)
            for bullet in exp.get('bullets', []):
                # Bullet point with indent
                pdf.set_x(22)
                pdf.cell(5, 5, chr(149))
                pdf.multi_cell(0, 5, str(bullet))
            pdf.ln(2)

    # ── Education ─────────────────────────────────────────────────────────
    education = tailored.get('education', [])
    if education:
        section_title("EDUCATION")
        for edu in education:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 41, 59)
            pdf.cell(0, 6,
                f"{edu.get('degree','')} — {edu.get('institution','')} {edu.get('year','')}",
                new_x="LMARGIN", new_y="NEXT")

    # Return as bytes
    return bytes(pdf.output())
